### PR TITLE
[*] MO : Blocklanguages add hreflang and rel alternate to the links for a better SEO and avoid duplicate content

### PR DESCRIPTION
**Pull request by cgordenne**

### CODE REVIEW

**Comment by gRoussac** [comment]
Hi,

Thank you for your PR. You probably wanted to affect current default template override too.

https://github.com/PrestaShop/PrestaShop/blob/develop/themes/default-bootstrap/modules/blocklanguages/blocklanguages.tpl

Regards

**Comment by cgordenne** [comment]
Hi @gRoussac 
Yes how can I do that properly in this PR ? Because we are here in the module's folder

**Comment by gRoussac** [comment]
Well sorry you can not =), both files are different sorry !

**Comment by cgordenne** [comment]
No problem :) So should I create a new PR for the template file ?

**Comment by gRoussac** [comment]
indeed ! or the merger should do it when merging this one.

**Comment by cgordenne** [comment]
Done : https://github.com/PrestaShop/PrestaShop/pull/3542

**Comment by gRoussac** [comment]
Hi,

thank you for your PR. Can you please add $language.iso_code|escape:'html':'UTF-8', i rather see it escaped.

Regards

**Comment by cgordenne** [comment]
Done

**Comment by gRoussac** [comment]
Hi,

thank you for you RP and contribution.

Best regards

**Pull request merged**
